version: "2"
services:
  web:
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    command: npm start
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"